root = "."
testdata_dir = "tests"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main internal/main.go"
  log = "air.log"
  delay = 1000
  exclude_dir = ["bin", "assets", "docs", "tmp", "vendor", "tests", "databases", "docker"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  send_interrupt = false
  stop_on_error = true

[watch]
  includes = ["./internal", "./pkg", "./configs"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false